#!/usr/bin/env bash
set -euo pipefail

[ -f ~/.secrets/mimo.sh ] && source ~/.secrets/mimo.sh

if [ -z "${MIMO_API_KEY:-}" ]; then
  echo "ERROR: MIMO_API_KEY is empty"
  exit 1
fi

unset ANTHROPIC_API_KEY
unset CLAUDE_CODE_USE_VERTEX
unset CLAUDE_CODE_USE_BEDROCK
unset ANTHROPIC_VERTEX_PROJECT_ID
unset ANTHROPIC_VERTEX_REGION
unset CLOUD_ML_REGION
unset GOOGLE_APPLICATION_CREDENTIALS
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_PROFILE
unset VOLCENGINE_API_KEY
unset DEEPSEEK_API_KEY

# Force non-thinking / non-reasoning route.
unset CLAUDE_CODE_EFFORT_LEVEL
unset CLAUDE_CODE_REASONING_EFFORT
unset CLAUDE_CODE_BUDGET_TOKENS
unset ANTHROPIC_BUDGET_TOKENS
unset EXTENDED_THINKING

export MIMO_BASE_URL="${MIMO_BASE_URL:-https://token-plan-cn.xiaomimimo.com/v1}"
export MIMO_ANTHROPIC_BASE_URL="${MIMO_ANTHROPIC_BASE_URL:-https://token-plan-cn.xiaomimimo.com/anthropic}"
CANONICAL_MIMO_MODEL="mimo-v2.5"
RAW_MIMO_MODEL="${MIMO_MODEL:-$CANONICAL_MIMO_MODEL}"
NORMALIZED_MIMO_MODEL="$(printf '%s' "$RAW_MIMO_MODEL" | tr '[:upper:]' '[:lower:]')"

if [ "$NORMALIZED_MIMO_MODEL" != "$CANONICAL_MIMO_MODEL" ]; then
  echo "ERROR: unsupported MIMO_MODEL '$RAW_MIMO_MODEL' (expected $CANONICAL_MIMO_MODEL)"
  exit 1
fi

export MIMO_MODEL="$CANONICAL_MIMO_MODEL"
export ANTHROPIC_BASE_URL="$MIMO_ANTHROPIC_BASE_URL"
export ANTHROPIC_AUTH_TOKEN="$MIMO_API_KEY"
export ANTHROPIC_MODEL="$CANONICAL_MIMO_MODEL"
export ANTHROPIC_DEFAULT_OPUS_MODEL="$CANONICAL_MIMO_MODEL"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$CANONICAL_MIMO_MODEL"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$CANONICAL_MIMO_MODEL"
export ANTHROPIC_SMALL_FAST_MODEL="$CANONICAL_MIMO_MODEL"
export CLAUDE_CODE_SUBAGENT_MODEL="$CANONICAL_MIMO_MODEL"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
export BASH_MAX_OUTPUT_LENGTH="12000"

echo "Claude route: mimo_full"
echo "MIMO_API_KEY length: ${#MIMO_API_KEY}"
echo "MIMO_ANTHROPIC_BASE_URL=$MIMO_ANTHROPIC_BASE_URL"
echo "MIMO_BASE_URL=$MIMO_BASE_URL"
echo "ANTHROPIC_MODEL=$ANTHROPIC_MODEL"

exec claude --permission-mode bypassPermissions --dangerously-skip-permissions "$@"
