"""T1865 - Frozen Backlog Manifest Renderer.

Pure functions to render a FrozenBacklogManifest as JSON or Markdown.
No I/O. No timestamps. No network.
"""
from __future__ import annotations

import json

from core.frozen_backlog_manifest import FrozenBacklogManifest


def render_manifest_json(manifest: FrozenBacklogManifest) -> str:
    """Render manifest as deterministic JSON string.

    Pure function. No I/O. No network.
    """
    payload = {
        "manifest_id": manifest.manifest_id,
        "generated_by": manifest.generated_by,
        "release_hold": manifest.release_hold,
        "no_live": manifest.no_live,
        "no_submit": manifest.no_submit,
        "no_exchange": manifest.no_exchange,
        "no_runtime_integration": manifest.no_runtime_integration,
        "no_planner_integration": manifest.no_planner_integration,
        "artifacts": [
            {
                "filename": a.filename,
                "size_bytes": a.size_bytes,
                "sha256_hash": a.sha256_hash,
            }
            for a in manifest.artifacts
        ],
    }
    return json.dumps(payload, sort_keys=True, indent=2)


def render_manifest_md(manifest: FrozenBacklogManifest) -> str:
    """Render manifest as markdown string.

    Pure function. No I/O. No network.
    """
    lines: list[str] = []
    lines.append("# Frozen Backlog Manifest")
    lines.append("")
    lines.append(f"**Manifest ID:** {manifest.manifest_id}")
    lines.append(f"**Generated By:** {manifest.generated_by}")
    lines.append(f"**Release Hold:** {manifest.release_hold}")
    lines.append("")
    lines.append("## Safety Flags")
    lines.append("")
    lines.append(f"- No Live: {manifest.no_live}")
    lines.append(f"- No Submit: {manifest.no_submit}")
    lines.append(f"- No Exchange: {manifest.no_exchange}")
    lines.append(f"- No Runtime Integration: {manifest.no_runtime_integration}")
    lines.append(f"- No Planner Integration: {manifest.no_planner_integration}")
    lines.append("")
    lines.append("## Artifacts")
    lines.append("")
    lines.append("| Filename | Size (bytes) | SHA-256 |")
    lines.append("|----------|-------------|---------|")
    for a in manifest.artifacts:
        short_hash = a.sha256_hash[:16] + "..."
        lines.append(f"| {a.filename} | {a.size_bytes} | {short_hash} |")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(
        "Frozen Backlog Review Platform v1 — Manifest. "
        "release_hold=HOLD enforced."
    )
    return "\n".join(lines)
