from typing import Optional


ORDER_STATUS_NEW = "NEW"
ORDER_STATUS_ACCEPTED = "ACCEPTED"
ORDER_STATUS_PARTIALLY_FILLED = "PARTIALLY_FILLED"
ORDER_STATUS_FILLED = "FILLED"
ORDER_STATUS_CANCELED = "CANCELED"
ORDER_STATUS_REJECTED = "REJECTED"

ORDER_EVENT_SUBMITTED = "ORDER_SUBMITTED"
ORDER_EVENT_ACCEPTED = "ORDER_ACCEPTED"
ORDER_EVENT_PARTIALLY_FILLED = "ORDER_PARTIALLY_FILLED"
ORDER_EVENT_FILLED = "ORDER_FILLED"
ORDER_EVENT_CANCELED = "ORDER_CANCELED"
ORDER_EVENT_REJECTED = "ORDER_REJECTED"

ORDER_STATUS_TRANSITIONS = {
    None: {
        ORDER_EVENT_SUBMITTED: ORDER_STATUS_NEW,
    },
    ORDER_STATUS_NEW: {
        ORDER_EVENT_ACCEPTED: ORDER_STATUS_ACCEPTED,
        ORDER_EVENT_CANCELED: ORDER_STATUS_CANCELED,
        ORDER_EVENT_REJECTED: ORDER_STATUS_REJECTED,
    },
    ORDER_STATUS_ACCEPTED: {
        ORDER_EVENT_PARTIALLY_FILLED: ORDER_STATUS_PARTIALLY_FILLED,
        ORDER_EVENT_FILLED: ORDER_STATUS_FILLED,
        ORDER_EVENT_CANCELED: ORDER_STATUS_CANCELED,
        ORDER_EVENT_REJECTED: ORDER_STATUS_REJECTED,
    },
    ORDER_STATUS_PARTIALLY_FILLED: {
        ORDER_EVENT_PARTIALLY_FILLED: ORDER_STATUS_PARTIALLY_FILLED,
        ORDER_EVENT_FILLED: ORDER_STATUS_FILLED,
        ORDER_EVENT_CANCELED: ORDER_STATUS_CANCELED,
    },
    ORDER_STATUS_FILLED: {},
    ORDER_STATUS_CANCELED: {},
    ORDER_STATUS_REJECTED: {},
}


def get_next_order_status(current_status: Optional[str], event_type: str) -> Optional[str]:
    allowed = ORDER_STATUS_TRANSITIONS.get(current_status, {})
    return allowed.get(event_type)


def is_valid_order_transition(current_status: Optional[str], event_type: str) -> bool:
    return get_next_order_status(current_status, event_type) is not None
