"""T902 — 500 backlog task factory.

Deterministic. No I/O. No timestamps. No random.
"""

from dataclasses import dataclass
from typing import Any, Dict, List

from core.prd_backlog_schema import PrdBacklogItem, build_backlog_item
from core.prd_500_backlog_domain_catalog import (
    Prd500BacklogDomain,
    build_prd_500_backlog_domain_catalog,
)
from core.prd_task_model import VALID_RISK_LEVELS, VALID_STATUSES

# --- Constants ---

LIVE_AUTHORIZATION_PHRASES = frozenset({
    "authorized for live trading",
    "authorized for real order placement",
})

TASK_FACTORY_NOTE = "auto-generated by prd_500_task_factory"


# --- Dataclass ---


@dataclass(frozen=True)
class Prd500TaskFactoryConfig:
    start_task_number: int
    target_task_count: int
    default_status: str
    notes: List[str]


# --- Defaults ---


def build_default_500_task_factory_config() -> Prd500TaskFactoryConfig:
    """Default config: start=901, target=550, status=NOT_STARTED."""
    return Prd500TaskFactoryConfig(
        start_task_number=901,
        target_task_count=550,
        default_status="NOT_STARTED",
        notes=["Default factory config for PRD 500-backlog generation."],
    )


# --- Core generators ---


def generate_tasks_for_domain(
    domain: Prd500BacklogDomain,
    start_task_number: int,
    count: int,
) -> List[PrdBacklogItem]:
    """Generate `count` tasks for given domain, starting at start_task_number.

    Pure deterministic. No I/O. No timestamps. No random.
    """
    if count < 0:
        raise ValueError(f"count must be >= 0, got {count}")
    if start_task_number < 1:
        raise ValueError(f"start_task_number must be >= 1, got {start_task_number}")

    tasks: List[PrdBacklogItem] = []
    is_frozen = domain.default_risk_level == "FROZEN"
    status = "HUMAN_REVIEW_REQUIRED" if is_frozen else "NOT_STARTED"
    acceptance = [] if is_frozen else ["pytest"]

    for i in range(count):
        task_number = start_task_number + i
        task_id = f"T{task_number}"
        title = f"{domain.title} -- task {i + 1}"
        deps: List[str] = []
        if i > 0:
            deps = [f"T{task_number - 1}"]

        notes = list(domain.notes) + [TASK_FACTORY_NOTE]

        item = build_backlog_item(
            task_id=task_id,
            title=title,
            milestone_id=domain.domain_id,
            wave_id=f"{domain.domain_id}-W0",
            batch_id=f"{domain.domain_id}-W0-B0",
            risk_level=domain.default_risk_level,
            status=status,
            dependencies=deps,
            allowed_file_patterns=list(domain.allowed_file_patterns),
            forbidden_file_patterns=list(domain.forbidden_file_patterns),
            acceptance_command_ids=acceptance,
            notes=notes,
        )
        tasks.append(item)

    return tasks


def generate_prd_500_backlog_tasks(
    target_task_count: int = 550,
    start_task_number: int = 901,
) -> List[PrdBacklogItem]:
    """Generate tasks across all domains.

    Iterates domains in catalog order. Each domain gets its target_task_count
    worth of tasks. Stops when total reaches target_task_count.
    """
    if target_task_count < 1:
        raise ValueError(f"target_task_count must be >= 1, got {target_task_count}")
    if start_task_number < 1:
        raise ValueError(f"start_task_number must be >= 1, got {start_task_number}")

    domains = build_prd_500_backlog_domain_catalog()
    all_tasks: List[PrdBacklogItem] = []
    current_task_number = start_task_number
    remaining = target_task_count

    for domain in domains:
        if remaining <= 0:
            break
        count = min(domain.target_task_count, remaining)
        domain_tasks = generate_tasks_for_domain(
            domain=domain,
            start_task_number=current_task_number,
            count=count,
        )
        all_tasks.extend(domain_tasks)
        current_task_number += count
        remaining -= count

    return all_tasks


# --- Serializers ---


def task_factory_config_to_dict(config: Prd500TaskFactoryConfig) -> Dict[str, Any]:
    """Convert factory config to plain dict."""
    return {
        "start_task_number": config.start_task_number,
        "target_task_count": config.target_task_count,
        "default_status": config.default_status,
        "notes": list(config.notes),
    }


def summarize_generated_tasks(tasks: List[PrdBacklogItem]) -> Dict[str, Any]:
    """Return summary dict of generated tasks."""
    status_counts: Dict[str, int] = {}
    risk_counts: Dict[str, int] = {}
    domain_counts: Dict[str, int] = {}

    for t in tasks:
        status_counts[t.status] = status_counts.get(t.status, 0) + 1
        risk_counts[t.risk_level] = risk_counts.get(t.risk_level, 0) + 1
        domain_counts[t.milestone_id] = domain_counts.get(t.milestone_id, 0) + 1

    task_ids = [t.task_id for t in tasks]
    numbers = [int(tid[1:]) for tid in task_ids]

    return {
        "total_tasks": len(tasks),
        "min_task_number": min(numbers) if numbers else None,
        "max_task_number": max(numbers) if numbers else None,
        "status_counts": status_counts,
        "risk_counts": risk_counts,
        "domain_counts": domain_counts,
        "unique_task_ids": len(set(task_ids)),
    }
