"""Research review audit trail.

Program F: Review Audit Trail.
Generates review_audit_trail.json and review_audit_trail.md.

No network. No exchange. No runtime. No planner.
"""
from __future__ import annotations

import hashlib
import json
from typing import Any, Dict, List, Tuple

AUDIT_TRAIL_VERSION = "1.0.0"


def build_audit_trail(
    input_artifact_hashes: Dict[str, str],
    output_artifact_hashes: Dict[str, str],
    command_args: List[str],
    generated_by: str = "research_human_review",
    generated_at: str = "deterministic",
) -> Dict[str, Any]:
    """Build review audit trail."""
    return {
        "schema_version": "1.0.0",
        "audit_trail_version": AUDIT_TRAIL_VERSION,
        "generated_at": generated_at,
        "generated_by": generated_by,
        "command_arguments": command_args,
        "input_artifact_hashes": input_artifact_hashes,
        "output_artifact_hashes": output_artifact_hashes,
        "deterministic_ordering": True,
        "release_hold": "HOLD",
        "advisory_only": True,
        "human_review_required": True,
        "no_live": True,
        "no_submit": True,
        "no_exchange": True,
        "no_network": True,
        "no_runtime_integration": True,
        "no_planner_integration": True,
        "no_auto_promotion": True,
        "no_auto_promotion_statement": (
            "No artifact in this audit trail authorizes live trading, "
            "testnet submission, runtime integration, planner integration, "
            "or auto-promotion."
        ),
    }


def validate_audit_trail_safety(trail: Dict[str, Any]) -> Tuple[bool, Tuple[str, ...]]:
    """Validate audit trail safety flags."""
    errors: List[str] = []

    checks = {
        "release_hold": "HOLD",
        "advisory_only": True,
        "human_review_required": True,
        "no_live": True,
        "no_submit": True,
        "no_exchange": True,
        "no_network": True,
        "no_runtime_integration": True,
        "no_planner_integration": True,
        "no_auto_promotion": True,
    }

    for key, expected in checks.items():
        actual = trail.get(key)
        if actual != expected:
            errors.append(f"{key}={actual!r}, expected {expected!r}")

    if not trail.get("deterministic_ordering", False):
        errors.append("deterministic_ordering must be True")

    return (len(errors) == 0, tuple(errors))


def compute_output_hashes_from_dict(artifacts: Dict[str, Any]) -> Dict[str, str]:
    """Compute deterministic hashes from artifact dict."""
    hashes: Dict[str, str] = {}
    for name in sorted(artifacts.keys()):
        content = json.dumps(artifacts[name], sort_keys=True, indent=2)
        hashes[name] = hashlib.sha256(content.encode()).hexdigest()
    return hashes


def render_audit_trail_markdown(trail: Dict[str, Any]) -> str:
    """Render audit trail as markdown."""
    lines: List[str] = []
    lines.append("# Review Audit Trail")
    lines.append("")
    lines.append(f"Version: {trail.get('audit_trail_version', 'unknown')}")
    lines.append(f"Generated: {trail.get('generated_at', 'unknown')}")
    lines.append(f"Generated by: {trail.get('generated_by', 'unknown')}")
    lines.append("")
    lines.append("## Safety Flags")
    lines.append("")
    flags = [
        "release_hold", "advisory_only", "human_review_required",
        "no_live", "no_submit", "no_exchange", "no_network",
        "no_runtime_integration", "no_planner_integration", "no_auto_promotion",
    ]
    for flag in flags:
        lines.append(f"- {flag} = {trail.get(flag, 'MISSING')}")
    lines.append("")
    lines.append("## Command Arguments")
    lines.append("")
    for arg in trail.get("command_arguments", []):
        lines.append(f"- `{arg}`")
    lines.append("")
    lines.append("## Input Artifact Hashes")
    lines.append("")
    for name, h in sorted(trail.get("input_artifact_hashes", {}).items()):
        lines.append(f"- `{name}`: `{h[:16]}...`")
    lines.append("")
    lines.append("## Output Artifact Hashes")
    lines.append("")
    for name, h in sorted(trail.get("output_artifact_hashes", {}).items()):
        lines.append(f"- `{name}`: `{h[:16]}...`")
    lines.append("")
    lines.append("## No Auto-Promotion Statement")
    lines.append("")
    lines.append(trail.get("no_auto_promotion_statement", ""))
    lines.append("")

    return "\n".join(lines)
