"""Research review report renderer.

Program G: Review Report Renderer.
Generates human_review_report.md and human_review_report.html.

No network. No exchange. No runtime. No planner.
"""
from __future__ import annotations

import html
from typing import Any, Dict, List


def render_review_markdown(
    packet: Dict[str, Any],
    checklist: Dict[str, Any],
    signoff_template: Dict[str, Any],
    blocker_ledger: Dict[str, Any],
    audit_trail: Dict[str, Any],
) -> str:
    """Render complete human review report as markdown."""
    lines: List[str] = []
    lines.append("# Human Review Report")
    lines.append("")

    # Section 1: Executive review status
    lines.append("## 1. Executive Review Status")
    lines.append("")
    lines.append(f"- Packet ID: {packet.get('packet_id', '')}")
    lines.append(f"- Generated: {packet.get('generated_at', '')}")
    lines.append(f"- Quality verdict: {packet.get('quality_verdict', '')}")
    lines.append(f"- Browser verdict: {packet.get('browser_verdict', '')}")
    lines.append(f"- Comparison verdict: {packet.get('comparison_verdict', '')}")
    lines.append(f"- Recommended decision: {packet.get('recommended_decision', '')}")
    lines.append(f"- Blocker count: {len(packet.get('blockers', []))}")
    lines.append("")

    # Section 2: Safety boundary
    lines.append("## 2. Safety Boundary")
    lines.append("")
    lines.append("- release_hold = HOLD")
    lines.append("- advisory_only = True")
    lines.append("- human_review_required = True")
    lines.append("- no_live = True")
    lines.append("- no_submit = True")
    lines.append("- no_exchange = True")
    lines.append("- no_network = True")
    lines.append("- no_runtime_integration = True")
    lines.append("- no_planner_integration = True")
    lines.append("")

    # Section 3: Source artifacts
    lines.append("## 3. Source Artifacts")
    lines.append("")
    for label, path in sorted(packet.get("source_dirs", {}).items()):
        lines.append(f"- {label}: `{path}`")
    lines.append("")
    lines.append("### Source Hashes")
    for name, h in sorted(packet.get("source_hashes", {}).items()):
        lines.append(f"- `{name}`: `{h[:16]}...`")
    lines.append("")

    # Section 4: Quality verdict
    lines.append("## 4. Quality Verdict")
    lines.append("")
    lines.append(f"Quality gate verdict: **{packet.get('quality_verdict', 'UNKNOWN')}**")
    lines.append("")

    # Section 5: Comparison verdict
    lines.append("## 5. Comparison Verdict")
    lines.append("")
    lines.append(f"Comparison analytics verdict: **{packet.get('comparison_verdict', 'UNKNOWN')}**")
    lines.append("")

    # Section 6: Blockers and warnings
    lines.append("## 6. Blockers and Warnings")
    lines.append("")
    for b in packet.get("blockers", []):
        sev = b.get("severity", "UNKNOWN")
        lines.append(f"- [{sev}] {b.get('blocker_id', 'UNKNOWN')}: {b.get('description', '')}")
    if not packet.get("blockers"):
        lines.append("- None")
    lines.append("")

    # Section 7: Human checklist
    lines.append("## 7. Human Checklist")
    lines.append("")
    lines.append(f"Total: {checklist.get('total_items', 0)} items")
    lines.append(f"Pending: {checklist.get('pending_items', 0)}")
    lines.append("")
    for idx, item in enumerate(checklist.get("items", []), 1):
        status = item.get("status", "PENDING")
        marker = "[ ]" if status == "PENDING" else "[x]"
        lines.append(f"{idx}. {marker} {item.get('label', '')}")
    lines.append("")

    # Section 8: Signoff instructions
    lines.append("## 8. Signoff Instructions")
    lines.append("")
    lines.append("Complete the signoff template with your decision.")
    lines.append("")
    lines.append("Allowed decisions:")
    for d in signoff_template.get("allowed_decisions", []):
        lines.append(f"- {d}")
    lines.append("")

    # Section 9: Blocker resolution ledger
    lines.append("## 9. Blocker Resolution Ledger")
    lines.append("")
    lines.append(f"Total blockers: {blocker_ledger.get('total_blockers', 0)}")
    lines.append(f"Open: {blocker_ledger.get('open_blockers', 0)}")
    lines.append("")
    for entry in blocker_ledger.get("entries", []):
        lines.append(
            f"- [{entry.get('status', 'OPEN')}] "
            f"{entry.get('blocker_id', '')} "
            f"(severity: {entry.get('severity', '')})"
        )
    lines.append("")

    # Section 10: Audit trail
    lines.append("## 10. Audit Trail")
    lines.append("")
    lines.append(f"Generated by: {audit_trail.get('generated_by', '')}")
    lines.append(f"Generated at: {audit_trail.get('generated_at', '')}")
    lines.append(f"Deterministic ordering: {audit_trail.get('deterministic_ordering', False)}")
    lines.append("")

    # Section 11: Allowed manual decisions
    lines.append("## 11. Allowed Manual Decisions")
    lines.append("")
    for d in packet.get("allowed_decisions", []):
        lines.append(f"- {d}")
    lines.append("")

    # Section 12: Forbidden decisions
    lines.append("## 12. Forbidden Decisions")
    lines.append("")
    for d in packet.get("forbidden_decisions", []):
        lines.append(f"- ~~{d}~~")
    lines.append("")

    # Section 13: Advisory-only statement
    lines.append("## 13. Advisory-Only Statement")
    lines.append("")
    lines.append("All research output in this review is advisory only.")
    lines.append("No decision authorizes live trading or execution.")
    lines.append("")

    # Section 14: No auto-promotion statement
    lines.append("## 14. No Auto-Promotion Statement")
    lines.append("")
    lines.append(packet.get("promotion_block_statement", ""))
    lines.append("")

    return "\n".join(lines)


def render_review_html(
    packet: Dict[str, Any],
    checklist: Dict[str, Any],
    signoff_template: Dict[str, Any],
    blocker_ledger: Dict[str, Any],
    audit_trail: Dict[str, Any],
) -> str:
    """Render complete human review report as standalone offline HTML."""
    h = html.escape

    def e(text: str) -> str:
        return h(str(text))

    blockers_html = ""
    for b in packet.get("blockers", []):
        sev = e(b.get("severity", "UNKNOWN"))
        bid = e(b.get("blocker_id", "UNKNOWN"))
        desc = e(b.get("description", ""))
        blockers_html += f"<tr><td>{sev}</td><td>{bid}</td><td>{desc}</td></tr>\n"
    if not blockers_html:
        blockers_html = "<tr><td colspan='3'>None</td></tr>"

    checklist_html = ""
    for idx, item in enumerate(checklist.get("items", []), 1):
        status = e(item.get("status", "PENDING"))
        label = e(item.get("label", ""))
        checklist_html += f"<tr><td>{idx}</td><td>{status}</td><td>{label}</td></tr>\n"

    ledger_html = ""
    for entry in blocker_ledger.get("entries", []):
        bid = e(entry.get("blocker_id", ""))
        sev = e(entry.get("severity", ""))
        status = e(entry.get("status", "OPEN"))
        ledger_html += f"<tr><td>{bid}</td><td>{sev}</td><td>{status}</td></tr>\n"

    source_hashes_html = ""
    for name, hsh in sorted(packet.get("source_hashes", {}).items()):
        source_hashes_html += f"<tr><td>{e(name)}</td><td><code>{e(hsh[:16])}...</code></td></tr>\n"

    allowed_decisions_html = ""
    for d in packet.get("allowed_decisions", []):
        allowed_decisions_html += f"<li>{e(d)}</li>\n"

    forbidden_decisions_html = ""
    for d in packet.get("forbidden_decisions", []):
        forbidden_decisions_html += f"<li><s>{e(d)}</s></li>\n"

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Human Review Report — {e(packet.get('packet_id', ''))}</title>
<style>
body {{ font-family: Arial, Helvetica, sans-serif; background: #fff; color: #222; margin: 2em; line-height: 1.6; }}
h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
h2 {{ border-bottom: 1px solid #ccc; padding-bottom: 0.2em; margin-top: 2em; }}
table {{ border-collapse: collapse; width: 100%; margin: 1em 0; }}
th, td {{ border: 1px solid #ccc; padding: 0.4em 0.6em; text-align: left; }}
th {{ background: #f5f5f5; }}
code {{ background: #f0f0f0; padding: 0.1em 0.3em; font-size: 0.9em; }}
.safety-box {{ background: #fff3cd; border: 1px solid #ffc107; padding: 1em; margin: 1em 0; }}
.forbidden {{ color: #c00; text-decoration: line-through; }}
ul {{ padding-left: 1.5em; }}
</style>
</head>
<body>

<h1>Human Review Report</h1>
<p>Packet: <code>{e(packet.get('packet_id', ''))}</code><br>
Generated: {e(packet.get('generated_at', ''))}</p>

<h2>1. Executive Review Status</h2>
<table>
<tr><th>Field</th><th>Value</th></tr>
<tr><td>Quality verdict</td><td>{e(packet.get('quality_verdict', ''))}</td></tr>
<tr><td>Browser verdict</td><td>{e(packet.get('browser_verdict', ''))}</td></tr>
<tr><td>Comparison verdict</td><td>{e(packet.get('comparison_verdict', ''))}</td></tr>
<tr><td>Recommended decision</td><td>{e(packet.get('recommended_decision', ''))}</td></tr>
<tr><td>Blocker count</td><td>{len(packet.get('blockers', []))}</td></tr>
</table>

<h2>2. Safety Boundary</h2>
<div class="safety-box">
<strong>release_hold = HOLD</strong><br>
advisory_only = True | human_review_required = True<br>
no_live = True | no_submit = True | no_exchange = True | no_network = True<br>
no_runtime_integration = True | no_planner_integration = True
</div>

<h2>3. Source Artifacts</h2>
<table>
<tr><th>Source</th><th>Path</th></tr>
{"".join(f"<tr><td>{e(label)}</td><td><code>{e(path)}</code></td></tr>" for label, path in sorted(packet.get("source_dirs", {}).items()))}
</table>
<h3>Source Hashes</h3>
<table>
<tr><th>Artifact</th><th>Hash (prefix)</th></tr>
{source_hashes_html}
</table>

<h2>4. Quality Verdict</h2>
<p><strong>{e(packet.get('quality_verdict', 'UNKNOWN'))}</strong></p>

<h2>5. Comparison Verdict</h2>
<p><strong>{e(packet.get('comparison_verdict', 'UNKNOWN'))}</strong></p>

<h2>6. Blockers and Warnings</h2>
<table>
<tr><th>Severity</th><th>ID</th><th>Description</th></tr>
{blockers_html}
</table>

<h2>7. Human Checklist</h2>
<p>Total: {checklist.get('total_items', 0)} | Pending: {checklist.get('pending_items', 0)}</p>
<table>
<tr><th>#</th><th>Status</th><th>Item</th></tr>
{checklist_html}
</table>

<h2>8. Signoff Instructions</h2>
<p>Complete the signoff template with your decision.</p>
<p>Allowed decisions:</p>
<ul>
{allowed_decisions_html}
</ul>

<h2>9. Blocker Resolution Ledger</h2>
<table>
<tr><th>Blocker</th><th>Severity</th><th>Status</th></tr>
{ledger_html}
</table>

<h2>10. Audit Trail</h2>
<p>Generated by: {e(audit_trail.get('generated_by', ''))}<br>
Generated at: {e(audit_trail.get('generated_at', ''))}<br>
Deterministic ordering: {e(str(audit_trail.get('deterministic_ordering', False)))}</p>

<h2>11. Allowed Manual Decisions</h2>
<ul>
{allowed_decisions_html}
</ul>

<h2>12. Forbidden Decisions</h2>
<ul>
{forbidden_decisions_html}
</ul>

<h2>13. Advisory-Only Statement</h2>
<p>All research output in this review is advisory only. No decision authorizes live trading or execution.</p>

<h2>14. No Auto-Promotion Statement</h2>
<p>{e(packet.get('promotion_block_statement', ''))}</p>

</body>
</html>"""


def validate_report_sections(markdown_content: str) -> bool:
    """Validate that markdown report contains required sections."""
    required = [
        "1. Executive Review Status",
        "2. Safety Boundary",
        "3. Source Artifacts",
        "4. Quality Verdict",
        "5. Comparison Verdict",
        "6. Blockers and Warnings",
        "7. Human Checklist",
        "8. Signoff Instructions",
        "9. Blocker Resolution Ledger",
        "10. Audit Trail",
        "11. Allowed Manual Decisions",
        "12. Forbidden Decisions",
        "13. Advisory-Only Statement",
        "14. No Auto-Promotion Statement",
    ]
    return all(section in markdown_content for section in required)


def validate_report_html_sections(html_content: str) -> bool:
    """Validate that HTML report contains required sections."""
    required = [
        "Executive Review Status",
        "Safety Boundary",
        "Source Artifacts",
        "Quality Verdict",
        "Comparison Verdict",
        "Blockers and Warnings",
        "Human Checklist",
        "Signoff Instructions",
        "Blocker Resolution Ledger",
        "Audit Trail",
        "Allowed Manual Decisions",
        "Forbidden Decisions",
        "Advisory-Only Statement",
        "No Auto-Promotion Statement",
    ]
    return all(section in html_content for section in required)
