"""Runtime governance route safety note builder (T822)."""


def build_runtime_governance_route_safety_note_markdown() -> str:
    """Pure deterministic markdown. No timestamps."""
    return (
        "# Runtime Governance Route Safety Note\n"
        "\n"
        "## Purpose\n"
        "\n"
        "Define routing rules for AI-assisted development tasks based on risk tier.\n"
        "\n"
        "## Risk Tiers\n"
        "\n"
        "### Low Risk -- Pure Docs / Tests\n"
        "\n"
        "- Routing: **mimo2.5** (standard model)\n"
        "- Examples: documentation edits, unit test additions, markdown updates\n"
        "- Autonomous execution permitted\n"
        "\n"
        "### Medium Risk -- Multi-Agent Dependency DAG\n"
        "\n"
        "- Routing: **mimo2.5pro** (reasoning model)\n"
        "- Examples: cross-module refactors, dependency graph changes, multi-file edits\n"
        "- Autonomous execution permitted with review gate\n"
        "\n"
        "### High Risk -- Live Submit / Secrets / Exchange\n"
        "\n"
        "- Routing: **human-controlled only**\n"
        "- Examples: live order submission, secret rotation, exchange credential changes\n"
        "- **NO autonomous live submit**\n"
        "- Requires explicit human approval before execution\n"
        "\n"
        "## Hard Constraint\n"
        "\n"
        "Autonomous live submit is never recommended. All exchange-facing actions\n"
        "require human-controlled oversight.\n"
    )
