#!/usr/bin/env python3
"""Temporary A/B research: indicators as overlays on existing strategy signals.

Research branch only; do not merge.

The base signals are generated by the repository's *existing* production
analysis path, not reimplemented here:

    core.paper_trading.strategy_registry.analyze_for_strategy

Each historical decision uses exactly the latest 120 completed bars, matching
the default live public-kline runner limit. Only HIGH/MEDIUM candidates are
eligible because `run_enabled_strategies.py` only forwards those candidates to
the TradeIntent pipeline.

Stage-1 scope is deliberately bounded to current 15m + 1h strategies:

MACD rebound (BTC/ETH/BNB/SUI/1000PEPE):
- BASELINE
- ACCEL_POSITIVE_NON_EXTREME: signed_speed > 0 and regime != EXTREME
- IRON_TOP_VETO: reject when Iron Top strength >= 1

Weak short (XRP/ARB/DOGE):
- BASELINE
- ACCEL_NEGATIVE_NON_EXTREME: signed_speed < 0 and regime != EXTREME
- BOTTOM_REVERSAL_VETO: reject exact known price event
  (prior-30 new low + close above previous bar low)
- IRON_TOP_CONFIRM: require Iron Top strength >= 1

No overlay combinations, no threshold tuning, no symbol selection, no 5m in
this stage. Entry is next-bar open after a completed signal bar. Existing
candidate stop/target prices are preserved; executable geometry is revalidated
at the actual next-bar fill. One exposure at a time per
strategy/symbol/timeframe/variant. Fee grid is 0 and 0.5 bp per side with zero
slippage; the 0.5 bp value is a transparent research stress input, NOT P1-03.
"""
from __future__ import annotations

from dataclasses import asdict
from datetime import datetime, timezone
import json
from pathlib import Path
import statistics
import sys

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from core.offline_backtest_metrics_engine import compute_run_metrics
from core.offline_backtest_trade_simulator import TradeSimulationParams, simulate_trade
from core.paper_trading.aicoin_indicator_ports import evaluate_iron_top
from core.paper_trading.indicator_composite_strategy import AccelerationRegime
from core.paper_trading.market_accelerator_port import (
    calculate_market_accelerator,
    classify_accelerator_series,
)
from core.paper_trading.strategy_registry import SignalCandidate, analyze_for_strategy
from core.paper_trading.trade_intent_risk_gate import validate_trade_intent
from scripts.run_indicator_composite_backtest import _load_historical, _market_bars

START = "2025-08-01"
END = "2026-07-31"
WINDOW_BARS = 120
MAX_HOLD_BARS = 100
FEE_BPS_GRID = (0.0, 0.5)
DATA_ROOT = Path("data/existing_strategy_overlay_history")

STRATEGY_SERIES = {
    "macd_rebound_watch": {
        "symbols": ("BTCUSDT", "ETHUSDT", "BNBUSDT", "SUIUSDT", "1000PEPEUSDT"),
        "timeframes": ("15m", "1h"),
        "variants": (
            "BASELINE",
            "ACCEL_POSITIVE_NON_EXTREME",
            "IRON_TOP_VETO",
        ),
    },
    "weak_short_watch": {
        "symbols": ("XRPUSDT", "ARBUSDT", "DOGEUSDT"),
        "timeframes": ("15m", "1h"),
        "variants": (
            "BASELINE",
            "ACCEL_NEGATIVE_NON_EXTREME",
            "BOTTOM_REVERSAL_VETO",
            "IRON_TOP_CONFIRM",
        ),
    },
}


def _bottom_reversal_event(bars, index: int) -> bool:
    if index < 30:
        return False
    current = bars[index]
    previous = bars[index - 1]
    prior = bars[index - 30:index]
    return (
        float(current.low) < min(float(bar.low) for bar in prior)
        and float(current.close) > float(previous.low)
    )


def _iron_strength(bars, index: int) -> int:
    # IronTop requires 61 bars with current default config. Keep a larger
    # 120-bar live-equivalent window so the function's historical baseline is
    # identical to normal use while still ending exactly at the decision bar.
    if index + 1 < WINDOW_BARS:
        return 0
    return evaluate_iron_top(bars[index - WINDOW_BARS + 1:index + 1]).strength


def _variant_accepts(
    strategy_type: str,
    variant: str,
    bars,
    index: int,
    accelerator_series,
    regimes,
) -> bool:
    if variant == "BASELINE":
        return True

    point = accelerator_series.points[index]
    regime = regimes[index].regime
    signed_speed = point.signed_speed

    if strategy_type == "macd_rebound_watch":
        if variant == "ACCEL_POSITIVE_NON_EXTREME":
            return (
                signed_speed is not None
                and signed_speed > 0
                and regime != AccelerationRegime.EXTREME
            )
        if variant == "IRON_TOP_VETO":
            return _iron_strength(bars, index) == 0

    if strategy_type == "weak_short_watch":
        if variant == "ACCEL_NEGATIVE_NON_EXTREME":
            return (
                signed_speed is not None
                and signed_speed < 0
                and regime != AccelerationRegime.EXTREME
            )
        if variant == "BOTTOM_REVERSAL_VETO":
            return not _bottom_reversal_event(bars, index)
        if variant == "IRON_TOP_CONFIRM":
            return _iron_strength(bars, index) >= 1

    raise ValueError(f"unknown overlay {strategy_type}/{variant}")


def _candidate_at(strategy_type: str, bars, index: int) -> SignalCandidate | None:
    if index + 1 < WINDOW_BARS:
        return None
    window = list(bars[index - WINDOW_BARS + 1:index + 1])
    result = analyze_for_strategy(
        strategy_id=strategy_type,
        strategy_type=strategy_type,
        bars=window,
    )
    candidate = result.candidate if result.success else None
    if candidate is None or candidate.priority not in {"HIGH", "MEDIUM"}:
        return None
    return candidate


def _bar_dict(bar) -> dict:
    return {
        "timestamp": float(bar.timestamp),
        "open": float(bar.open),
        "high": float(bar.high),
        "low": float(bar.low),
        "close": float(bar.close),
        "volume": float(bar.volume),
        "symbol": str(bar.symbol),
        "timeframe": str(bar.timeframe),
    }


def _simulate_variant(
    *,
    strategy_type: str,
    symbol: str,
    timeframe: str,
    variant: str,
    bars,
    candidates: list[SignalCandidate | None],
    accelerator_series,
    regimes,
    fee_bps: float,
) -> dict:
    params = TradeSimulationParams(
        fee_pct=fee_bps / 10000.0,
        slippage_pct=0.0,
        max_hold_bars=MAX_HOLD_BARS,
    )
    bar_dicts = [_bar_dict(bar) for bar in bars]
    unavailable_until = -1
    base_candidate_count = 0
    overlay_pass_count = 0
    blocked_no_next_bar = 0
    blocked_execution_geometry = 0
    blocked_overlap = 0
    trades: list[dict] = []

    for signal_index, candidate in enumerate(candidates):
        if candidate is None:
            continue
        base_candidate_count += 1
        if not _variant_accepts(
            strategy_type,
            variant,
            bars,
            signal_index,
            accelerator_series,
            regimes,
        ):
            continue
        overlay_pass_count += 1

        entry_index = signal_index + 1
        if entry_index >= len(bars):
            blocked_no_next_bar += 1
            continue
        if entry_index <= unavailable_until:
            blocked_overlap += 1
            continue

        entry_price = float(bars[entry_index].open)
        stop_price = float(candidate.invalidation_level)
        target_price = float(candidate.take_profit_observation)
        side = "LONG" if candidate.direction == "LONG_OBSERVE" else "SHORT"

        if side == "LONG":
            risk = entry_price - stop_price
            reward = target_price - entry_price
        else:
            risk = stop_price - entry_price
            reward = entry_price - target_price

        if entry_price <= 0 or risk <= 0 or reward <= 0:
            blocked_execution_geometry += 1
            continue

        risk_pct = risk / entry_price * 100.0
        reward_pct = reward / entry_price * 100.0
        actual_rr = reward / risk
        gate = validate_trade_intent({
            "execution_mode": "shadow_only",
            "side": side,
            "intent_status": "SHADOW_READY",
            "rr_ratio": actual_rr,
            "risk_distance_pct": risk_pct,
            "reward_distance_pct": reward_pct,
            "max_risk_pct": 0.5,
            "entry_price": entry_price,
            "stop_loss": stop_price,
            "take_profit": target_price,
        })
        if not gate.passed:
            blocked_execution_geometry += 1
            continue

        outcome = simulate_trade(
            {
                "signal_id": (
                    f"overlay_{strategy_type}_{symbol}_{timeframe}_{variant}_{signal_index}"
                ),
                "entry_bar_index": entry_index,
                "entry_execution": "bar_open",
                "entry_price": entry_price,
                "stop_price": stop_price,
                "tp_price": target_price,
            },
            bar_dicts,
            params,
        )
        trades.append({
            "trade_id": outcome.trade_id,
            "signal_id": outcome.signal_id,
            "strategy_type": strategy_type,
            "symbol": symbol,
            "timeframe": timeframe,
            "variant": variant,
            "side": side,
            "signal_index": signal_index,
            "entry_bar_index": outcome.entry_bar_index,
            "exit_bar_index": outcome.exit_bar_index,
            "realized_r": outcome.realized_r,
            "gross_pnl": outcome.gross_pnl,
            "fees": outcome.fees,
            "slippage_cost": outcome.slippage_cost,
            "net_pnl": outcome.net_pnl,
            "mfe_r": outcome.mfe_r,
            "mae_r": outcome.mae_r,
            "hold_bars": outcome.hold_bars,
            "planned_watch_state": candidate.watch_state,
            "planned_priority": candidate.priority,
            "planned_rr": candidate.rr_ratio,
            "actual_rr_at_fill": round(actual_rr, 6),
            "signal_time": float(bars[signal_index].timestamp),
        })
        unavailable_until = outcome.exit_bar_index

    metrics = compute_run_metrics(trades)
    return {
        "strategy_type": strategy_type,
        "symbol": symbol,
        "timeframe": timeframe,
        "variant": variant,
        "fee_bps_per_side": fee_bps,
        "base_candidate_count": base_candidate_count,
        "overlay_pass_count": overlay_pass_count,
        "overlay_candidate_coverage": (
            round(overlay_pass_count / base_candidate_count, 6)
            if base_candidate_count else 0.0
        ),
        "blocked_no_next_bar": blocked_no_next_bar,
        "blocked_execution_geometry": blocked_execution_geometry,
        "blocked_overlap": blocked_overlap,
        "trade_count": len(trades),
        "metrics": metrics,
        "trades": trades,
    }


def _aggregate(results: list[dict], strategy_type: str, variant: str, fee_bps: float) -> dict:
    selected = [
        result for result in results
        if result["strategy_type"] == strategy_type
        and result["variant"] == variant
        and result["fee_bps_per_side"] == fee_bps
    ]
    trades = [trade for result in selected for trade in result["trades"]]
    metrics = compute_run_metrics(trades)
    base_candidates = sum(result["base_candidate_count"] for result in selected)
    passed_candidates = sum(result["overlay_pass_count"] for result in selected)
    positive_series = [
        f"{result['symbol']}:{result['timeframe']}"
        for result in selected
        if float(result["metrics"]["expectancy_r"]) > 0
    ]
    return {
        "strategy_type": strategy_type,
        "variant": variant,
        "fee_bps_per_side": fee_bps,
        "series_count": len(selected),
        "base_candidate_count": base_candidates,
        "overlay_pass_count": passed_candidates,
        "overlay_candidate_coverage": (
            round(passed_candidates / base_candidates, 6)
            if base_candidates else 0.0
        ),
        "trade_count": len(trades),
        "win_rate": metrics["win_rate"],
        "expectancy_r": metrics["expectancy_r"],
        "profit_factor": metrics["profit_factor"],
        "max_drawdown_r_not_portfolio_valid": metrics["max_drawdown_r"],
        "avg_mfe_r": metrics["avg_mfe_r"],
        "avg_mae_r": metrics["avg_mae_r"],
        "avg_hold_bars": metrics["avg_hold_bars"],
        "positive_expectancy_series": positive_series,
        "positive_series_count": len(positive_series),
        "portfolio_drawdown_not_computed": True,
    }


def main() -> int:
    results: list[dict] = []

    for strategy_type, spec in STRATEGY_SERIES.items():
        for symbol in spec["symbols"]:
            for timeframe in spec["timeframes"]:
                path = DATA_ROOT / symbol / f"{symbol}_{timeframe}.csv"
                history = _load_historical(path, symbol, timeframe, 1000)
                bars = _market_bars(history)
                accelerator = calculate_market_accelerator(bars)
                regimes = classify_accelerator_series(accelerator.points)

                candidates: list[SignalCandidate | None] = [None] * len(bars)
                for index in range(WINDOW_BARS - 1, len(bars)):
                    candidates[index] = _candidate_at(strategy_type, bars, index)

                for variant in spec["variants"]:
                    for fee_bps in FEE_BPS_GRID:
                        result = _simulate_variant(
                            strategy_type=strategy_type,
                            symbol=symbol,
                            timeframe=timeframe,
                            variant=variant,
                            bars=bars,
                            candidates=candidates,
                            accelerator_series=accelerator,
                            regimes=regimes,
                            fee_bps=fee_bps,
                        )
                        results.append(result)
                        compact = result["metrics"]
                        print(
                            strategy_type,
                            symbol,
                            timeframe,
                            variant,
                            f"fee={fee_bps}bp",
                            f"candidates={result['base_candidate_count']}",
                            f"coverage={result['overlay_candidate_coverage']}",
                            f"trades={result['trade_count']}",
                            f"pf={compact['profit_factor']}",
                            f"exp={compact['expectancy_r']}",
                        )

    aggregate = {}
    for strategy_type, spec in STRATEGY_SERIES.items():
        aggregate[strategy_type] = {}
        for variant in spec["variants"]:
            aggregate[strategy_type][variant] = {
                str(fee_bps): _aggregate(results, strategy_type, variant, fee_bps)
                for fee_bps in FEE_BPS_GRID
            }

    output = {
        "experiment_id": "existing_strategy_indicator_overlays_stage1_v1",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "period": f"{START}..{END}",
        "decision_window_bars": WINDOW_BARS,
        "timeframes": ["15m", "1h"],
        "excluded_timeframes": ["5m"],
        "existing_strategy_logic_reimplemented": False,
        "candidate_authority": "core.paper_trading.strategy_registry.analyze_for_strategy",
        "priority_contract": "HIGH_MEDIUM_ONLY_matches_run_enabled_strategies_payload",
        "entry_execution": "closed_signal_next_bar_open_v1",
        "existing_candidate_stop_target_preserved": True,
        "actual_fill_geometry_revalidated": True,
        "max_hold_bars": MAX_HOLD_BARS,
        "fee_grid_bps_per_side": list(FEE_BPS_GRID),
        "fee_grid_status": "hypothetical_research_stress_not_p1_03",
        "slippage_pct": 0.0,
        "overlay_combinations": False,
        "threshold_tuning": False,
        "symbol_selection": False,
        "aggregate": aggregate,
        "per_series": [
            {
                key: value
                for key, value in result.items()
                if key != "trades"
            }
            for result in results
        ],
        "safety": [
            "OFFLINE_RESEARCH_ONLY",
            "PUBLIC_HISTORY_ONLY",
            "NO_PRODUCTION_CHANGE",
            "NO_P1_03_ACTIVATION",
            "NO_TESTNET",
            "NO_LIVE",
            "NO_ORDER",
            "NO_ACCOUNT",
            "NO_SECRET",
        ],
    }

    destination = Path("research_results/existing_strategy_indicator_overlays_stage1.json")
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(output, indent=2), encoding="utf-8")

    print("=== AGGREGATE ===")
    for strategy_type, variants in aggregate.items():
        print("STRATEGY", strategy_type)
        for variant, fees in variants.items():
            for fee, values in fees.items():
                print(variant, "fee", fee, values)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
